server:
  port: 88

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://google.com
          predicates:
            - Query=url,google

        - id: yahoo_route
          uri: https://yahoo.com
          predicates:
            - Query=url,yahoo

        - id: product_route
          uri: lb://shoppingmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
  application:
    name: shoppingmall-gateway
