server:
  port: 88

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://shoppingmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://shoppingmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_service_route
          uri: lb://shoppingmall-third-service
          predicates:
            - Path=/api/thirdserivce/**
          filters:
            - RewritePath=/api/thirdserivce/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://shoppingmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://shoppingmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: shoppingmall-host-router
          uri: lb://shoppingmall-product
          predicates:
            - Host=shoppingmall.com,item.shoppingmall.com

        - id: shoppingmall-search-router
          uri: lb://shoppingmall-search
          predicates:
            - Host=search.shoppingmall.com

        - id: shoppingmall-auth-router
          uri: lb://shoppingmall-auth-server
          predicates:
            - Host=auth.shoppingmall.com

        - id: shoppingmall-cart-router
          uri: lb://shoppingmall-cart
          predicates:
            - Host=cart.shoppingmall.com

        - id: shoppingmall-order-router
          uri: lb://shoppingmall-order
          predicates:
            - Host=order.shoppingmall.com

        - id: shoppingmall-member-router
          uri: lb://shoppingmall-member
          predicates:
            - Host=member.shoppingmall.com

        - id: shoppingmall-seckill-router
          uri: lb://shoppingmall-seckill
          predicates:
            - Host=seckill.shoppingmall.com