server:
  port: 9000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.157.129:3306/shoppingmall_order_manage

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.157.129
    port: 5672
    virtual-host: /
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.157.129
  application:
    name: shoppingmall-order
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    tw.yu.shoppingmall: debug

shoppingmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

myRabbitmq:
  MQConfig:
    queues: order.release.order.queue
    delayQueue: order.delay.queue
    eventExchange: order-event-exchange
    routingKey: order.release.order
    createOrder: order.create.order
    ReleaseOther: stock.release.stock.queue
    ReleaseOtherKey: order.release.other
    ttl: 900000